Resources:
  S3CrBucketCommon:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      BucketName: cr-perlin-common-${self:provider.stage}
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
  S3CrBucketCommonBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: !Ref 'S3CrBucketCommon'
        PolicyDocument:
          Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: '*'
            Action: s3:GetObject
            Resource: !Join ['', ['arn:aws:s3:::', !Ref 'S3CrBucketCommon', /*]]
