service: bs-carbon-registry-services

provider:
  name: aws
  runtime: nodejs16.x
  stage: ${opt:stage, 'prod'}
  region: us-east-1
  environment:
    PROJECT_NAME: ${self:service}
    NODE_ENV: ${self:provider.stage}
    FILE_SERVICE: 'S3'
    LOG_LEVEL: 'debug'
    DOMAIN_MAP: 'false'
    SOURCE_EMAIL: 'admin@bioeconomy.co'
    NODE_PATH: './:/opt/node_modules'
    STAGE: ${self:provider.stage}
    LEDGER_TYPE: QLDB #QLDB, PGSQL
    IS_EMAIL_DISABLED: 'false'
    DISABLE_LOW_PRIORITY_EMAIL: 'true'
    ASYNC_OPERATIONS_TYPE: Queue
    LOCATION_SERVICE: FILE
    COUNTRY_NAME: 'Bahamas'
    COUNTRY_CODE: 'BS'
  # iam:
  #   role: arn:aws:iam::909101490035:role/lambda-role
  # vpc:
  #   subnetIds:
  #     - subnet-05abb4287f3081602
  #     - subnet-09148cfff6c5e97b1
  #   securityGroupIds:
  #     - sg-0bf65b90711ab2043

package:
  patterns:
    - "!node_modules/**"
    - ".env"
    - .env.${self:provider.stage}
    - "countries.json"
    - "regions.csv"
    - "src/i18n/**"

plugins:
  - serverless-iam-roles-per-function
  - serverless-plugin-typescript
  - serverless-plugin-optimize
  - serverless-offline
  - serverless-domain-manager
  - serverless-ssm-fetch
#  - '@haftahave/serverless-ses-template'

# params:
#   local:
#     depLayerArn1: arn:aws:lambda:us-west-2:111111111111:layer:layer:1
#     depLayerArn2: arn:aws:lambda:us-west-2:111111111111:layer:layer:1

functions:
  - ${file(./iaac/v1-api.yml)}
  - ${file(./iaac/v1-handlers.yml)}

custom:
  customDomain: ${file(./iaac/gateway/dns.yml):customDomain}
  optimize:
    external: ["swagger-ui-dist"]
  serverlessSsmFetch:
    USER_JWT_SECRET: /${self:service}/${self:provider.stage}/USER_JWT_SECRET~true
    ADMIN_JWT_SECRET: /${self:service}/${self:provider.stage}/ADMIN_JWT_SECRET~true
    DB_PASSWORD: /${self:service}/${self:provider.stage}/DB_PASSWORD~true
    SMTP_USERNAME: /${self:service}/${self:provider.stage}/SMTP_USERNAME~true
    SMTP_PASSWORD: /${self:service}/${self:provider.stage}/SMTP_PASSWORD~true
    MAPBOX_PK: /${self:service}/${self:provider.stage}/MAPBOX_PK~true
    ITMO_API_KEY: /${self:service}/${self:provider.stage}/ITMO_API_KEY~true
    ITMO_EMAIL: /${self:service}/${self:provider.stage}/ITMO_EMAIL~true
    ITMO_PASSWORD: /${self:service}/${self:provider.stage}/ITMO_PASSWORD~true
    MRV_API_TOKEN: /${self:service}/${self:provider.stage}/MRV_API_TOKEN~true
    PERL_LEDGER_PROVIDER_URL: /${self:service}/${self:provider.stage}/PERL_LEDGER_PROVIDER_URL~true
    PERL_LEDGER_CONTRACT_ADDRESS: /${self:service}/${self:provider.stage}/PERL_LEDGER_CONTRACT_ADDRESS~true
    PERL_LEDGER_WALLET_PRIVATE_KEY: /${self:service}/${self:provider.stage}/PERL_LEDGER_WALLET_PRIVATE_KEY~true
  # sesTemplates:
  #   addStage: true                             # Specifies whether to add stage to template name (default false)
  #   configFile: './src/shared/email/email.template.ts' # Config file path (default './ses-email-templates/index.js')
  #   region: 'us-east-1'

resources:
  - ${file(./iaac/gateway/defaults.yml)}
  - ${file(./iaac/v1-databases.yml)}
  - ${file(./iaac/v1-queues.yml)}
  - ${file(./iaac/v1-ledger.yml)}
  - ${file(./iaac/v1-buckets.yml)}
