export enum CompanyType {
   PARTNERSHIP = 'Partnership',
   PRIVATELY_TRADING_COMPANIES = 'Privately Trading Companies',
   PUBLICLY_TRADING_COMPANIES = 'Publicly Trading Companies',
   LIMITED_LIABILITY_PARTNERSHIPS = 'Limited Liability Partnerships',
   LIMITED_LIABILITY_COMPANY = 'Limited Liability Company',
   INTERNATIONAL_BUSINESS_CORPORATION = 'International Business Corporation',
   EXEMPTED_LIMITED_PARTNERSHIP = 'Exempted Limited Partnership',
   FOREIGN_COMPANIES = 'Foreign Companies',
   SOLE_PROPRIETORSHIPS = 'Sole-Proprietorships',
   FOUNDATIONS = 'Foundations',
   NON_GOVERNMENTAL_ORGANIZATIONS = 'Non-governmental Organizations',
   CIVIL_SOCIETY = 'Civil Society',
   GOVERNMENT_ENTITY = 'Government Entity',
   OTHER = 'Other',
}