service: lambda-layer

provider:
  name: aws
  runtime: nodejs16.x
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  # iam:
  #   role: arn:aws:iam::909101490035:role/lambda-role
  # vpc:
  #   subnetIds:
  #     - subnet-05abb4287f3081602 Private Subnet (AZ1)
  #     - subnet-09148cfff6c5e97b1 Private Subnet (AZ2)
  #   securityGroupIds:
  #     - sg-0bf65b90711ab2043

layers:
  blockchain-dependencies:
    path: dependency_layer
    name: blockchain-dependencies-${self:provider.stage}
    description: "Blockchain Dependencies"
    package:
      exclude:
        - node_modules/**
        - '!node_modules/ethers/**'
  service-dependencies-1:
    path: dependency_layer
    name: service-dependencies-${self:provider.stage}-1
    description: "Node Modules Dependencies 1"
    package:
      exclude:
        - node_modules/**
        - '!node_modules/@*/**'
        - '!node_modules/a*/**'
        - '!node_modules/b*/**'
        - '!node_modules/c*/**'
  service-dependencies-2:
    path: dependency_layer
    name: service-dependencies-${self:provider.stage}-2
    description: "Node Modules Dependencies 2"
    package:
      exclude:
        - 'node_modules/@*/**'
        - 'node_modules/a*/**'
        - 'node_modules/b*/**'
        - 'node_modules/c*/**'